packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  bcrypt: true
  esbuild: set this to true or false
  prisma: set this to true or false

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - "bcrypt"
  - "esbuild"
  - "prisma"
